// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7MGJ7vz9MiWv3atlHBcslZHCuZ9nEHE',
    appId: '1:558964717392:web:69fe1c146883d26497de55',
    messagingSenderId: '558964717392',
    projectId: 'spacenews-core-cfbd4',
    authDomain: 'spacenews-core-cfbd4.firebaseapp.com',
    storageBucket: 'spacenews-core-cfbd4.firebasestorage.app',
    measurementId: 'G-WBN9WZE01S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFaEAn57ZfmXnBbOvnaEFkv6ED-WLeI0k',
    appId: '1:558964717392:android:d82d1b39d5f4ea3597de55',
    messagingSenderId: '558964717392',
    projectId: 'spacenews-core-cfbd4',
    storageBucket: 'spacenews-core-cfbd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_UQBPO-Szpjt5tzDX5Qr7wGX5yIhtS4',
    appId: '1:558964717392:ios:15d40c98b73279fd97de55',
    messagingSenderId: '558964717392',
    projectId: 'spacenews-core-cfbd4',
    storageBucket: 'spacenews-core-cfbd4.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_UQBPO-Szpjt5tzDX5Qr7wGX5yIhtS4',
    appId: '1:558964717392:ios:15d40c98b73279fd97de55',
    messagingSenderId: '558964717392',
    projectId: 'spacenews-core-cfbd4',
    storageBucket: 'spacenews-core-cfbd4.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs7MGJ7vz9MiWv3atlHBcslZHCuZ9nEHE',
    appId: '1:558964717392:web:7978bce950b46cbe97de55',
    messagingSenderId: '558964717392',
    projectId: 'spacenews-core-cfbd4',
    authDomain: 'spacenews-core-cfbd4.firebaseapp.com',
    storageBucket: 'spacenews-core-cfbd4.firebasestorage.app',
    measurementId: 'G-5F688L1HC4',
  );
}
